### ISSUE TITLE
Fix non-compliant input files.

### ISSUE THREAD

**Issue by katyhuff** [pyrk/pyrk#36]
I noticed today that a number of the current input files in the examples directory aren't working any more. That's a problem. For each non-working input file, find the errors causing it to fail and:
- make any needed fixes to the pyrk software code, with an appropriate unit test that would catch the regression error in the future
- make any needed fixes to the input file, with appropriate checks on input parsing that would warn a user of the error. 

The following input files fail with an out-of-bounds index to either lambda or beta in the precursor data (`
  File "../../../../pyrk/driver.py", line 120, in y0
    si.ne._pd.betas()[j]/(si.ne._pd.lambdas()[j]*si.ne._pd._Lambda)
IndexError: list index out of range`):
- [ ] examples/pbfhr/multi_pt/prt_2ref/input_10s.py
- [ ] examples/pbfhr/multi_pt/prt_2ref/input_1s.py
- [ ] examples/pbfhr/multi_pt/prt_2ref/input_2s.py
- [ ] examples/pbfhr/multi_pt/prt_2ref/input_5s.py

The following fail with `AttributeError: 'DensityModel' object has no attribute 'to'`
- [ ] examples/pbfhr/multi_pt/prt_pke/input.py
- [x] examples/pbfhr/sensitivity/input.py

**Comment by gbremer** [comment]
Going through issues -- can this be closed? Was this addressed with the fix in #37?

**Comment by katyhuff** [comment]
#37 only addressed half of this issue. Some still fail, last I checked.

**Comment by gbremer** [comment]
A couple examples fail with import errors due to, I assume, LiquidMaterial moving modules. Another is an error where a unit.Quantity needs to be created so that it can be converted --

$ python examples/sfr/input.py 
Traceback (most recent call last):
  File "examples/sfr/input.py", line 80, in <module>
    k_fuel = 0.16*(units.watt/units.centimeter/units.kelvin).to('watt/meter/kelvin')
AttributeError: 'Unit' object has no attribute 'to'

My proposed change, that gets the module compiling, is this --

diff --git a/examples/sfr/input.py b/examples/sfr/input.py
index 4b52a74..0e41a0d 100644
--- a/examples/sfr/input.py
+++ b/examples/sfr/input.py
@@ -77,7 +77,9 @@ h_cool = 1.0e5*units.joule/units.second/units.kelvin/pow(units.meter, 2)
 
 # custom thermal resistance, ragusa
 w = 4.0/9.0
-k_fuel = 0.16*(units.watt/units.centimeter/units.kelvin).to('watt/meter/kelvin')
+k_fuel = units.Quantity(0.16, (units.watt /
+                               units.centimeter /
+                               units.kelvin)).to('watt/meter/kelvin')
 res_fuel = a_fuel*(1.0/(r_clad*2.0*math.pi*h_cool)
                    + w/(4.0*math.pi*k_fuel))/vol_fuel
 
This results in k_fuel as a Quantity --

>>> k_fuel
<Quantity(16.0, 'watt / kelvin / meter')>

Is that right?

**Comment by katyhuff** [comment]
yep - go for it.

**Comment by katyhuff** [comment]
Thanks!
